[package]
name = "numworks_rust"
version = "0.1.0"
authors = ["willemml <willem@leit.so>"]
edition = "2018"

[dependencies]
cortex-m = "0.6"
panic-halt = "0.2"
stm32f7xx-hal = { version = "0.3.0", features = ["stm32f730", "rt"] }
embedded-hal = "0.2"
cortex-m-rtic = "0.5.6"

[[bin]]
name = "numworks_rust"
test = false
bench = false

[profile.release]
codegen-units = 1
debug = true
lto = true
