[package]
name = "rustworks"
version = "0.0.1"
authors = ["willemml <willem@leit.so>"]
edition = "2018"
license = "GPL-3.0"
description = "An operating system for the Numworks n0110 calculator."
repository = "https://github.com/willemml/rustworks"
homepage = "https://github.com/willemml/rustworks"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
rtt-target = { version = "0.3", features = ["cortex-m"] }
alloc-cortex-m = "0.4.1"
embedded-hal = "0.2"
cortex-m-rtic = "0.5"
embedded-graphics = "0.6"
embedded-text = { version = "0.4", default-features = false }
heapless = "0.7"
st7789 = { version = "0.5", features = ["batch"] }
display-interface-parallel-gpio = "0.6"
stm32f7xx-hal = { git = "https://github.com/willemml/stm32f7xx-hal", branch = "fsmc_lcd", features = ["stm32f730", "rt", "fmc_lcd"] }
num-traits = { version = "0.2", default-features = false }
num-derive = "0.3"

[[bin]]
name = "rustworks"
test = false
bench = false

[profile.dev.package."*"]
opt-level = "s"

[profile.dev]
opt-level = "s"
debug = 1
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[profile.release.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 1
panic = "abort"
opt-level = "s"
lto = true
