[package]
name = "numworks_rust"
version = "0.1.0"
authors = ["willemml <willem@leit.so>"]
edition = "2018"

[dependencies]
cortex-m = "0.6"
panic-halt = "0.2"
stm32f7xx-hal = { git = "https://github.com/willemml/stm32f7xx-hal", branch = "fsmc_lcd", features = ["stm32f730", "rt", "fmc"] }
embedded-hal = "0.2"
cortex-m-rtic = "0.5.6"
embedded-graphics = "0.6.1"
st7789 = { path = "../st7789", version = "0.5.0" }

[[bin]]
name = "numworks_rust"
test = false
bench = false

[profile.release]
codegen-units = 1
debug = true
lto = true
