[default.probe]
protocol = "Swd"
speed = 2000

[default.flashing]
enabled = true

[default.reset]
enabled = true

[default.general]
chip = "stm32f730V8Tx"

[default.rtt]
enabled = true
timeout = 2
show_timestamps = true

